version = 1
 
[[analyzers]]
    name = "javascript"
    enabled = true
    [analyzers.meta]
        plugins =["react"]
        environment = ["mongo", "nodejs" , "browser"]
        module_system = "es-modules"
        dependency_file_paths = [
            "/package.json",
            "/tsconfig.json",
        ]
        
[[transformers]]
    name = "prettier"
    enabled = true